import os
import smtplib

from email.message import EmailMessage
from dotenv import load_dotenv


# ============================================================
# ENVIRONMENT CONFIGURATION
# ============================================================

load_dotenv()

SMTP_HOST = os.getenv(
    "SMTP_HOST",
    "smtp.gmail.com",
)

SMTP_PORT = int(
    os.getenv(
        "SMTP_PORT",
        "587",
    )
)

SMTP_EMAIL = os.getenv(
    "SMTP_EMAIL",
    "",
)

SMTP_PASSWORD = os.getenv(
    "SMTP_PASSWORD",
    "",
)

SMTP_SENDER_NAME = os.getenv(
    "SMTP_SENDER_NAME",
    "VisionGuard AI",
)


# ============================================================
# EMAIL CONFIGURATION CHECK
# ============================================================

def is_email_configured():

    return bool(
        SMTP_EMAIL
        and SMTP_PASSWORD
    )


# ============================================================
# SEND INSPECTION REPORT
# ============================================================

def send_inspection_report(
    recipient_email: str,
    inspection: dict,
    pdf_buffer,
):

    if not is_email_configured():

        raise RuntimeError(
            "Email service is not configured. "
            "Please configure SMTP_EMAIL and SMTP_PASSWORD."
        )

    inspection_code = inspection.get(
        "inspection_code",
        "VisionGuard-Inspection",
    )

    product = inspection.get(
        "product_category",
        "Unknown Product",
    )

    decision = inspection.get(
        "decision",
        "UNKNOWN",
    )

    severity = inspection.get(
        "severity",
        "NONE",
    )

    affected_area = float(
        inspection.get(
            "affected_area",
            0,
        )
        or 0
    )

    created_at = inspection.get(
        "created_at",
        "Unknown",
    )

    # ========================================================
    # CREATE EMAIL
    # ========================================================

    message = EmailMessage()

    message["From"] = (
        f"{SMTP_SENDER_NAME} <{SMTP_EMAIL}>"
    )

    message["To"] = recipient_email

    message["Subject"] = (
        f"VisionGuard Inspection Report - "
        f"{inspection_code}"
    )

    # ========================================================
    # EMAIL BODY
    # ========================================================

    message.set_content(
        f"""
VisionGuard Industrial Quality Inspection

Inspection ID: {inspection_code}
Product: {product}
Inspection Date: {created_at}

Inspection Result: {decision}
Severity: {severity}
Affected Area: {affected_area:.2f}%

The complete VisionGuard inspection report is attached
to this email as a PDF document.

This report was automatically generated by the
VisionGuard AI Industrial Quality Control System.

VisionGuard AI
Industrial Quality Control
        """.strip()
    )

    # ========================================================
    # PDF ATTACHMENT
    # ========================================================

    pdf_buffer.seek(0)

    pdf_bytes = pdf_buffer.read()

    pdf_filename = (
        f"VisionGuard_{inspection_code}_Report.pdf"
    )

    message.add_attachment(
        pdf_bytes,
        maintype="application",
        subtype="pdf",
        filename=pdf_filename,
    )

    # ========================================================
    # SEND USING SMTP
    # ========================================================

    with smtplib.SMTP(
        SMTP_HOST,
        SMTP_PORT,
        timeout=30,
    ) as smtp:

        smtp.ehlo()

        smtp.starttls()

        smtp.ehlo()

        smtp.login(
            SMTP_EMAIL,
            SMTP_PASSWORD,
        )

        smtp.send_message(
            message
        )

    return {
        "success": True,
        "recipient": recipient_email,
        "inspection_code": inspection_code,
        "filename": pdf_filename,
    }